### ISSUE TITLE
How to make this project in windows?

### ISSUE THREAD

**Issue by AliHassanEB** [0x2152Yet/yet_another_motor_drive#1]
Hi,
I am working on a different library "SimpleFOC" for ESP32 Microcontroller. In your code you have implemented estimation algorithm for Rotor angle and speed. Can I use these algorithms with that library because they haven't Implemented sensorless FOC yet but it is in their Roadmap.

https://github.com/simplefoc/Arduino-FOC 
https://docs.simplefoc.com/roadmap

**Comment by 0x2152Yet** [comment]
Hi,

Yes, you are free to use any of the code in the “Yet Another Motor Drive” repository with no restriction.

Thanks for asking!

Mike Kaufman

**Comment by AliHassanEB** [comment]
Thank You.
